COUNTRIES = [
  { name: "Albania", flag: "albania" },
  { name: "Armenia", flag: "armenia" },
  { name: "Australia", flag: "australia" },
  { name: "Austria", flag: "austria" },
  { name: "Azerbaijan", flag: "azerbaijan" },
  { name: "Belarus", flag: "belarus" },
  { name: "Belgium", flag: "belgium" },
  { name: "Bulgaria", flag: "bulgaria" },
  { name: "Croatia", flag: "croatia" },
  { name: "Cyprus", flag: "cyprus" },
  { name: "Czech Republic", flag: "czechia" },
  { name: "Czechia", flag: "czechia" },
  { name: "Denmark", flag: "denmark" },
  { name: "Estonia", flag: "estonia" },
  { name: "Finland", flag: "finland" },
  { name: "France", flag: "france" },
  { name: "FYR Macedonia", flag: "north_macedonia" },
  { name: "Georgia", flag: "georgia" },
  { name: "Germany", flag: "germany" },
  { name: "Greece", flag: "greece" },
  { name: "Hungary", flag: "hungary" },
  { name: "Iceland", flag: "iceland" },
  { name: "Ireland", flag: "ireland" },
  { name: "Israel", flag: "israel" },
  { name: "Italy", flag: "italy" },
  { name: "Latvia", flag: "latvia" },
  { name: "Lithuania", flag: "lithuania" },
  { name: "Luxembourg", flag: "luxembourg" },
  { name: "Malta", flag: "malta" },
  { name: "Moldova", flag: "moldova" },
  { name: "Montenegro", flag: "montenegro" },
  { name: "North Macedonia", flag: "north_macedonia" },
  { name: "Norway", flag: "norway" },
  { name: "Poland", flag: "poland" },
  { name: "Portugal", flag: "portugal" },
  { name: "Romania", flag: "romania" },
  { name: "Russia", flag: "russia" },
  { name: "San Marino", flag: "san_marino" },
  { name: "Serbia", flag: "serbia" },
  { name: "Slovenia", flag: "slovenia" },
  { name: "Spain", flag: "spain" },
  { name: "Sweden", flag: "sweden" },
  { name: "Switzerland", flag: "switzerland" },
  { name: "The Netherlands", flag: "netherlands" },
  { name: "Ukraine", flag: "ukraine" },
  { name: "United Kingdom", flag: "united_kingdom" },
].freeze
