inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
